In [2]:
#Bibek Shiwakoti
"""Learning openCV for the image processing"""

'Learning openCV for the image processing'

In [2]:
import numpy as np
import cv2

In [4]:
# pip install opencv-python (installed opencv for python)

     --------------------------------------- 38.6/38.6 MB 40.9 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
# pip freeze (making sure py seeing in pip freeze) 

In [8]:
img = cv2.imread('./images/bird.jpg')

In [9]:
print(img)

[[[23 17 28]
  [23 17 28]
  [23 17 28]
  ...
  [23 18 27]
  [23 18 27]
  [23 18 27]]

 [[23 17 28]
  [23 17 28]
  [23 17 28]
  ...
  [23 18 27]
  [23 18 27]
  [23 18 27]]

 [[23 17 28]
  [23 17 28]
  [23 17 28]
  ...
  [23 18 27]
  [23 18 27]
  [23 18 27]]

 ...

 [[23 18 27]
  [23 18 27]
  [23 18 27]
  ...
  [23 18 27]
  [23 18 27]
  [23 18 27]]

 [[23 18 27]
  [23 18 27]
  [23 18 27]
  ...
  [23 18 27]
  [23 18 27]
  [23 18 27]]

 [[23 18 27]
  [23 18 27]
  [23 18 27]
  ...
  [23 18 27]
  [23 18 27]
  [23 18 27]]]


In [13]:
img.shape

(148, 244, 3)

In [22]:
cv2.imshow('bird window example',img)
cv2.waitKey(5000) #milliseconds
cv2.destroyAllWindows()

In [23]:
cv2.imshow('bird window example',img)
cv2.waitKey(0) #image holds until and unless we press the button
cv2.destroyAllWindows()

## Save an image

In [24]:
cv2.imwrite('./images/example.png',img)

True